IFNMG-ESTAGIO/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', function () {
    return view('welcome');
})->name('/');

Route::group(['middleware' => ['can:user.admin']], function() {
    Route::post('/aluno','AlunoController@index')->name('aluno.filtro');
    Route::resource('aluno','AlunoController');
    Route::get('/aluno/{aluno_id}/pdf/{documento}','AlunoController@showPdf')->name('aluno.pdf');
    Route::get('/aluno/{aluno_id}/fotos/{foto}','AlunoController@showFoto')->name('aluno.foto');
    Route::post('/aluno/{aluno_id}/destroyPdf','AlunoController@destroyPdf')->name('aluno.destroyPdf');

    Route::resource('areaAtuacao','AreaAtuacaoController');

    Route::resource('convenio','ConveniosController');
    Route::get('/convenio/{convenio_id}/pdf/cadastro_convenio','ConveniosController@showPdf')->name('convenio.pdf');
    Route::post('/convenio/{convenio_id}/destroyPdf','ConveniosController@destroyPdf')->name('convenio.destroyPdf');

    Route::resource('curso','CursoController');
    Route::resource('estagio','EstagiosController');
    Route::get('/estagio/create/{aluno_id}','EstagiosController@create')->name('estagio.create()');
    Route::get('/estagio/{estagio_id}/edit/{aluno_id}','EstagiosController@edit')->name('estagio.edit()');
    Route::get('/estagio/{estagio_id}/pdf/{documento}','EstagiosController@showPdf')->name('estagio.pdf');
    Route::post('/estagio/{estagio_id}/destroyPdf','EstagiosController@destroyPdf')->name('estagio.destroyPdf');
    Route::delete('/estagio/{estagio_id}/destroy/{aluno_id}','EstagiosController@destroy')->name('estagio.destroy()');

    Route::resource('pessoa','PessoaController');

    Route::resource('professor','ProfessoresController');
    Route::resource('documento','DocumentosController');

});
Route::group(['middleware' => ['can:user.verMeuEstagio']], function() {
    Route::get('/meusEstagios','AlunoController@meusEstágios')->name('aluno.meusEstagios');
    Route::get('/meusEstagios/{aluno_id}','AlunoController@meusEstágios')->name('aluno.meuEstagio');
    Route::get('/estagio/{estagio_id}/pdf/{documento}','EstagiosController@showPdf')->name('estagio.pdf');
});

Route::get('/convenio','ConveniosController@index')->name('convenio.indexPublic');
Route::get('/documento','DocumentosController@index')->name('documento.indexPublic');
Route::get('/home', 'HomeController@index')->name('home');

Route::get('/convenio/public/{convenio}','ConveniosController@show')->name('convenio.abrir');
Route::get('/documento/public/{documentos}','DocumentosController@show')->name('documento.abrir');
Route::get('/convenio/{convenio_id}/pdf/cadastro_convenio','ConveniosController@showPdf')->name('convenio.pdf');

IFNMG-ESTAGIO/app/Alunos.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Pessoas;
use App\Cursos;
use App\Estagios;

class Alunos extends Model
{
    protected $table = 'aluno';
    public $fillable = [
        'id',
        'pessoa_id',
        'curso_id',
        'matricula',
        'turma',
        'foto',
        'situacao_estagio',
        'ficha_matricula',
        'access',
    ];
    protected $hidden = ['access'];
    
    public function curso() {
        return $this->belongsTo('App\Cursos');
    }
    
    public function pessoa() {
        return $this->belongsTo('App\Pessoas');
    }
    public function estagios()
    {
        return $this->hasMany('App\Estagios', 'aluno_id');
    }
    public function getCargaHorariaAttribute() {
        return $this->estagios->sum('carga_horaria');
    }
    public function getNomeAttribute() {
        return $this->pessoa->nome;
    }
    
    public function checkStatus() {
        $situacao_estagio = 'Em Andamento';
        
        $carga_horaria = $this->carga_horaria;
        $estagios_em_andamento = $this->estagios()->where('situacao','!=','Concluído')->get();
        
        if($carga_horaria >= (int)($this->curso->carga_horaria) && ($estagios_em_andamento->count() == 0)) {
            $situacao_estagio = 'Finalizado';
        }
        
        if($this->situacao_estagio != $situacao_estagio) {
            $this->update(['situacao_estagio' => $situacao_estagio]);
        }
    }
}

IFNMG-ESTAGIO/app/Http/Controllers/AlunoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Storage;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;

use Auth;
use App\Alunos;
use App\Cursos;
use App\Estagios;
use App\Pessoas;
use App\User;

class AlunoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $access = Auth::user()->access ?? env('APP_ACCESS');

        $alunos = Alunos::where('access', $access)->orderBy('id','DESC')->get();

        return view('aluno.index',compact('alunos'));
    }
    /**
     * Caso tenha mais de um registro de aluno para o usuário retorna uma lista para seleção. Caso não, informa o detalhamento do único estágio
     *
     * @param  int $aluno_id
     * @return \Illuminate\Http\Response
     */
    public function meusEstágios($aluno_id = null)
    {
        $aluno = Alunos::find($aluno_id);

        if($aluno) {
            $aluno->pessoa->nascimento = implode('/',array_reverse(explode('-',$aluno->pessoa->nascimento)));

            return view('aluno.meuEstagio', ['aluno'=>$aluno])->with('warning','Você possúi apenas um estágio cadastrado');
        };

        $alunos = Alunos::whereHas('pessoa', function($query) {
                $query->where([
                    ['nome', Auth::user()->name],
                    ['email', Auth::user()->email],
                    ['access', Auth::user()->access],
                ]);
            })->orderBy('id','DESC')->get();

        if($alunos->count() < 1)
            return redirect()->route('documento.indexPublic')
                ->with('error','Você não possúi estágio cadastrado');

        else if($alunos->count() == 1) {
            $aluno = $alunos->first();
            $aluno->pessoa->nascimento = implode('/',array_reverse(explode('-',$aluno->pessoa->nascimento)));

            return view('aluno.meuEstagio', ['aluno'=>$aluno])->with('warning','Você possúi apenas um estágio cadastrado');
        }
        return view('aluno.meusEstagios',compact('alunos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $retorno = Cursos::orderBy('id','DESC')->get();
        $cursos;
        foreach($retorno as $curso) {
            $cursos[$curso->id] = $curso->nome;
        }
        $error = 0;
        $errorMessage = [];
        if(empty($cursos)) {
            $cursos = [];
            $errorMessage[] = 'Não existem cursos cadastrados;';
            $error = true;
        }

        $cursos[0] = '';

        if($error)
            return view('aluno.create', ['cursos'=> $cursos])->withErrors($errorMessage);

        return view('aluno.create', ['cursos'=> $cursos]);
    }

    protected function validator(array $data)
    {
        return Validator::make($data, [
            'nome' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:6|confirmed',
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $messages = [
            'required'  => 'Campo Obrigratório.',
        ];
        // Validação dos campos necessários
        $this->validate($request, [
            'nome' => 'required',
            'turma' => 'required',
            'cidade_natal' => 'required',
            'uf_cidade_natal' => 'required',
            'nascimento' => 'required',
            'filiacao' => 'required',
            'estado_civil' => 'required',
            'sexo' => 'required',
            'rg' => 'required',
            'orgao_expeditor' => 'required',
            'cpf' => 'required',
            'email' => 'required',
            'endereco' => 'required',
            'numero' => 'required',
            'bairro' => 'required',
            'cidade' => 'required',
            'uf' => 'required',
            'cep' => 'required',
            'ficha_matricula' => 'required',
            'matricula' => 'required|unique:aluno',
        ], [
            'matricula.unique' => 'Esse Número da Matrícula já está sendo usado sistema, coloque outro número de matrícula',
            'cpf.required' => 'Campo Obrigratório',
            'nome.required' => 'Campo Obrigratório',
            'turma.required' => 'Campo Obrigratório',
            'cidade_natal.required' => 'Campo Obrigratório',
            'uf_cidade_natal.required' => 'Campo Obrigratório',
            'nascimento.required' => 'Campo Obrigratório',
            'filiacao.required' => 'Campo Obrigratório',
            'estado_civil.required' => 'Campo Obrigratório',
            'sexo.required' => 'Campo Obrigratório',
            'rg.required' => 'Campo Obrigratório',
            'orgao_expeditor.required' => 'Campo Obrigratório',
            'email.required' => 'Campo Obrigratório',
            'endereco.required' => 'Campo Obrigratório',
            'numero.required' => 'Campo Obrigratório',
            'bairro.required' => 'Campo Obrigratório',
            'cidade.required' => 'Campo Obrigratório',
            'uf.required' => 'Campo Obrigratório',
            'cep.required' => 'Campo Obrigratório',
            'ficha_matricula.required' => 'Campo Obrigratório',
            'matricula.required' => 'Campo Obrigratório',
        ]);

        // Formatação dos campos necessários
        $request['nascimento'] = implode('-',array_reverse(explode('/',$request->nascimento)));

        // Adição do controle de acesso
        $request['access'] = Auth::user()->access;

        // Salva os dados de pessoa na tabela pessoa, pegando o id para relacionamento
        $pessoa = Pessoas::create($request->all());

        $aluno = Alunos::create([
            'pessoa_id' => $pessoa->id,
            'curso_id' => $request->curso_id,
            'matricula' => $request->matricula,
            'turma' => $request->turma,
            'access' => Auth::user()->access,
        ]);

        // UPLOAD DOS ARQUIVOS
        if($request->file('ficha_matricula') != null) {
            $path_ficha_matricula = $request->file('ficha_matricula')
                ->storeAs("aluno/$aluno->id/pdfs","ficha_matricula.pdf");
            $aluno_data['ficha_matricula'] = 'true';

            $aluno->update($aluno_data);
        }

        if($request->file('foto') != null) {
            $path_ficha_matricula = $request->file('foto')
                ->storeAs("aluno/$aluno->id/fotos",$request->foto->getClientOriginalName());
            $aluno_foto['foto'] = $request->foto->getClientOriginalName();

            $aluno->update($aluno_foto);
        }
        
        $credencial = User::where([
            ['email', $pessoa->email],
            ['access', Auth::user()->access],
            ['auth', 'aluno'],
        ])->first();
        
        if (!$credencial) {
            $credencial = User::create([
                'name' => $pessoa->nome,
                'email' => $pessoa->email,
                'password' => bcrypt(preg_replace("/[^0-9]/","",$pessoa->cpf)),
                'access' => Auth::user()->access,
                'auth' => 'aluno',
            ]);
        }

        return redirect()->route('aluno.index')
            ->with('success','Registro salvo com sucesso');
    }

    /**
     * Display the specified resource.
     *
     * @param  Alunos  $aluno
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, $id)
    {
        $aluno = Alunos::findOrFail($id);

        $aluno->pessoa->nascimento = implode('/',array_reverse(explode('-',$aluno->pessoa->nascimento)));

        $estagios = Estagios::where('aluno_id','=',$id)->orderBy('id','DESC')->get();

        return view('aluno.show',['estagios'=>$estagios, 'aluno'=>$aluno]);

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Alunos  $aluno
     * @return \Illuminate\Http\Response
     */
    public function edit(Alunos $aluno)
    {
        if (Gate::denies('aluno.controlar', $aluno)) {
            return abort(403, "Você não tem acesso a esta função");
        }

        $aluno->pessoa->nascimento = implode('/',array_reverse(explode('-',$aluno->pessoa->nascimento)));

        $retorno = Cursos::orderBy('id','DESC')->get();
        $cursos;
        foreach($retorno as $curso) {
            $cursos[$curso->id] = $curso->nome;
        }
        $error = 0;
        $errorMessage = [];
        if(empty($cursos)) {
            $cursos = [];
            $errorMessage[] = 'Não existem cursos cadastrados;';
            $error = true;
        }

        if($error)
            return view('aluno.edit',['aluno'=>$aluno, 'cursos'=>$cursos])->withErrors($errorMessage);

        return view('aluno.edit',['aluno'=>$aluno, 'cursos'=>$cursos]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  Alunos  $aluno
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Alunos $aluno)
    {
        if (Gate::denies('aluno.controlar', $aluno)) {
            return abort(403, "Você não tem acesso a esta função");
        }

        // Validação dos campos necessários
        $this->validate($request, [
            'nome' => 'required',
            'cidade_natal' => 'required',
            'turma' => 'required',
            'uf_cidade_natal' => 'required',
            'nascimento' => 'required',
            'filiacao' => 'required',
            'estado_civil' => 'required',
            'sexo' => 'required',
            'rg' => 'required',
            'orgao_expeditor' => 'required',

IFNMG-ESTAGIO/resources/views/aluno/index.blade.php
@extends('layouts.app')
 
@section('content')
<?php
use Illuminate\Support\Facades\Input;?>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                @if ($message = Session::get('success'))
                    <div class="alert alert-success">
                        <p>{{ $message }}</p>
                    </div>
                @endif
                @if ($message = Session::get('error'))
                    <div class="alert alert-danger">
                        <p>{{ $message }}</p>
                    </div>
                @endif
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-md-9">Listagem de Alunos</div>
                            @can('user.admin')
                                <div class="text-right col-md-3"><a class="btn btn-default btn-sm" href="{{ route('aluno.create') }}" role="button">Novo Aluno</a></div>
                            @endcan
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped table-ordering" >
                                <thead>
                                    <tr>
                                        <th>Nome</th>
                                        <th>CPF</th>
                                        <th>N° Matrícula</th>
                                        <th width="150px" >Horas cumpridas</th>
                                        <th width="200px">Ação</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($alunos as $key => $aluno)
                                    <tr>
                                        <td>{{ $aluno->pessoa->nome }}</td>
                                        <td>{{ $aluno->pessoa->cpf }}</td>
                                        <td class="text-right">{{ $aluno->matricula }}</td>
                                        <td class="text-right">{{ $aluno->carga_horaria }}</td>
                                        <td>
                                            <a class="btn btn-default btn-sm" href="{{ route('aluno.show',$aluno->id) }}">Abrir</a>
                                            <a class="btn btn-primary btn-sm" href="{{ route('aluno.edit',$aluno->id) }}">Editar</a>
                                            {!! Form::open(['method' => 'DELETE','route' => ['aluno.destroy', $aluno->id],'style'=>'display:inline','class'=>'form-delete-cofirm', 'data-confirmed'=>'false']) !!}
                                            {!! Form::submit('Delete', ['class' => 'btn btn-danger btn-sm']) !!}
                                            {!! Form::close() !!}
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

IFNMG-ESTAGIO/resources/views/aluno/meusEstagios.blade.php
@extends('layouts.app')
 
@section('content')
<?php
use Illuminate\Support\Facades\Input;?>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                @if ($message = Session::get('success'))
                    <div class="alert alert-success">
                        <p>{{ $message }}</p>
                    </div>
                @endif
                @if ($message = Session::get('error'))
                    <div class="alert alert-danger">
                        <p>{{ $message }}</p>
                    </div>
                @endif
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-md-9">Listagem de Alunos</div>
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped table-ordering" >
                                <thead>
                                    <tr>
                                        <th>Curso</th>
                                        <th width="150px" >Horas cumpridas</th>
                                        <th width="50px" >Ação</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($alunos as $key => $aluno)
                                    <tr>
                                        <td>{{ $aluno->curso->nome }}</td>
                                        <td class="text-right">{{ $aluno->carga_horaria }}</td>
                                        <td>
                                            <a class="btn btn-default btn-sm" href="{{ route('aluno.meuEstagio',$aluno->id) }}">Abrir</a>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

IFNMG-ESTAGIO/resources/views/aluno/show.blade.php
@extends('layouts.app')
 
@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="row">
                <div class="col-lg-12 margin-tb">
                    <div class="pull-left">
                        <h2> Visualização de Aluno</h2>
                    </div>
                    <a href="{{ route('aluno.index') }}">
                        <div class="btn btn-danger pull-right">
                            Voltar
                        </div>
                    </a>
                </div>
            </div>

            <div class="row">
                <div class="col-xs-12 col-sm-6 col-md-6">
                    <div class="form-group">
                        <strong>Nome:</strong>
                        {{ $aluno->pessoa->nome }}
                    </div>
                </div>

                <div class="col-xs-6 col-sm-3 col-md-3">
                    <div class="form-group">
                        <strong>Cidade Natal:</strong>
                        {{ $aluno->pessoa->cidade_natal }}
                    </div>
                </div>

                <div class="col-xs-6 col-sm-3 col-md-3">
                    <div class="form-group">
                        <strong>UF Cidade Natal:</strong>
                        {{ $aluno->pessoa->uf_cidade_natal }}
                    </div>
                </div>

                <div class="col-xs-6 col-sm-3 col-md-3">
                    <div class="form-group">
                        <strong>Nascimento:</strong>
                        {{ $aluno->pessoa->nascimento }}
                    </div>
                </div>

                <div class="col-xs-6 col-sm-6 col-md-6">
                    <div class="form-group">
                        <strong>Filiação:</strong>
                        {{ $aluno->pessoa->filiacao }}
                    </div>
                </div>

                <div class="col-xs-6 col-sm-3 col-md-3">
                    <div class="form-group">
                        <strong>Estado Civil:</strong>
                        {{ $aluno->pessoa->estado_civil }}
                    </div>
                </div>

                <div class="col-xs-6 col-sm-2 col-md-2">
                    <div class="form-group">
                        <strong>Sexo:</strong>
                        {{ $aluno->pessoa->sexo }}
                    </div>
                </div>

                <div class="col-xs-12 col-sm-4 col-md-4">
                    <div class="form-group">
                        <strong>RG:</strong>
                        {{ $aluno->pessoa->rg }}
                    </div>
                </div>

                <div class="col-xs-6 col-sm-3 col-md-3">
                    <div class="form-group">
                        <strong>Orgão Expeditor:</strong>
                        {{ $aluno->pessoa->orgao_expeditor }}
                    </div>
                </div>

                <div class="col-xs-6 col-sm-3 col-md-3">
                    <div class="form-group">
                        <strong>CPF:</strong>
                        {{ $aluno->pessoa->cpf }}
                    </div>
                </div>

                <div class="col-xs-12 col-sm-4 col-md-4">
                    <div class="form-group">
                        <strong>Celular:</strong>
                        {{ $aluno->pessoa->celular }}
                    </div>
                </div>

                <div class="col-xs-12 col-sm-4 col-md-4">
                    <div class="form-group">
                        <strong>Telefone:</strong>
                        {{ $aluno->pessoa->telefone }}
                    </div>
                </div>

                <div class="col-xs-12 col-sm-4 col-md-4">
                    <div class="form-group">
                        <strong>Email:</strong>
                        {{ $aluno->pessoa->email }}
                    </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-5">
                    <div class="form-group">
                        <strong>Curso:</strong>
                        {{ $aluno->curso->nome }}
                    </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-2">
                    <div class="form-group">
                        <strong>Matricula:</strong>
                        {{ $aluno->matricula }}
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-5">
                    <div class="form-group">
                        <strong>Turma:</strong>
                        {{ $aluno->turma }}
                    </div>
                </div>
                
            </div>
            <div class="row">
                <div class="col-md-3 col-md-offset-3">
                    <div class="row ">&nbsp;</div>
                    <a class='btn btn-default' href="{{route('aluno.pdf',[$aluno->id,'ficha_matricula'])}}" target="_blank">Visualizar Ficha Matrícula</a>
                </div>
                <div class="col-md-3">
                    <div class="row ">&nbsp;</div>
                    <a class='btn btn-default' href="{{route('aluno.foto',[$aluno->id,$aluno->foto])}}" target="_blank">Visualizar Foto Do Aluno</a>
                </div>
            </div>

            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-10 col-md-offset-1">

            @if ($message = Session::get('success'))
                <div class="alert alert-success">
                    <p>{{ $message }}</p>
                </div>
            @endif
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-md-9">Lista de Estágio</div>
                        @can('user.admin')
                            <div class="text-right col-md-3"><a class="btn btn-default btn-sm" href="{{ route('estagio.create()',$aluno->id) }}" role="button">Novo Estágio</a></div>
                        @endcan
                    </div>
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped table-ordering" table-paging="false" table-max-height="100">
                            <thead>
                                <tr>
                                    <th>Convênio</th>
                                    <th>Orientador</th>
                                    <th width="150px">Horas Cumpridas</th>
                                    <th width="200px">Ação</th>
                                </tr>
                            </thead>
                            <tbody>
                            @foreach ($estagios as $key => $estagio)
                                <tr>
                                    <td>{{ $estagio->convenio->nome }}</td>
                                    <td>{{ $estagio->professor->nome }}</td>
                                    <td>{{ $estagio->carga_horaria }}</td>
                                    <td>
                                        <a class="btn btn-default btn-sm" href="{{ route('estagio.show',$estagio->id) }}">Abrir</a>
                                        <a class="btn btn-primary btn-sm" href="{{ route('estagio.edit',$estagio->id) }}">Editar</a>
                                        {!! Form::open(['method' => 'DELETE','route' => ['estagio.destroy()', $estagio->id, $aluno->id],'style'=>'display:inline']) !!}
                                        {!! Form::submit('Delete', ['class' => 'btn btn-danger btn-sm']) !!}
                                        {!! Form::close() !!}
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection