IFNMG-ESTAGIO/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', function () {
    return view('welcome');
})->name('/');

Route::group(['middleware' => ['can:user.admin']], function() {
    Route::post('/aluno','AlunoController@index')->name('aluno.filtro');
    Route::resource('aluno','AlunoController');
    Route::get('/aluno/{aluno_id}/pdf/{documento}','AlunoController@showPdf')->name('aluno.pdf');
    Route::get('/aluno/{aluno_id}/fotos/{foto}','AlunoController@showFoto')->name('aluno.foto');
    Route::post('/aluno/{aluno_id}/destroyPdf','AlunoController@destroyPdf')->name('aluno.destroyPdf');

    Route::resource('areaAtuacao','AreaAtuacaoController');

    Route::resource('convenio','ConveniosController');
    Route::get('/convenio/{convenio_id}/pdf/cadastro_convenio','ConveniosController@showPdf')->name('convenio.pdf');
    Route::post('/convenio/{convenio_id}/destroyPdf','ConveniosController@destroyPdf')->name('convenio.destroyPdf');

    Route::resource('curso','CursoController');
    Route::resource('estagio','EstagiosController');
    Route::get('/estagio/create/{aluno_id}','EstagiosController@create')->name('estagio.create()');
    Route::get('/estagio/{estagio_id}/edit/{aluno_id}','EstagiosController@edit')->name('estagio.edit()');
    Route::get('/estagio/{estagio_id}/pdf/{documento}','EstagiosController@showPdf')->name('estagio.pdf');
    Route::post('/estagio/{estagio_id}/destroyPdf','EstagiosController@destroyPdf')->name('estagio.destroyPdf');
    Route::delete('/estagio/{estagio_id}/destroy/{aluno_id}','EstagiosController@destroy')->name('estagio.destroy()');

    Route::resource('pessoa','PessoaController');

    Route::resource('professor','ProfessoresController');
    Route::resource('documento','DocumentosController');

});
Route::group(['middleware' => ['can:user.verMeuEstagio']], function() {
    Route::get('/meusEstagios','AlunoController@meusEstágios')->name('aluno.meusEstagios');
    Route::get('/meusEstagios/{aluno_id}','AlunoController@meusEstágios')->name('aluno.meuEstagio');
    Route::get('/estagio/{estagio_id}/pdf/{documento}','EstagiosController@showPdf')->name('estagio.pdf');
});

Route::get('/convenio','ConveniosController@index')->name('convenio.indexPublic');
Route::get('/documento','DocumentosController@index')->name('documento.indexPublic');
Route::get('/home', 'HomeController@index')->name('home');

Route::get('/convenio/public/{convenio}','ConveniosController@show')->name('convenio.abrir');
Route::get('/documento/public/{documentos}','DocumentosController@show')->name('documento.abrir');
Route::get('/convenio/{convenio_id}/pdf/cadastro_convenio','ConveniosController@showPdf')->name('convenio.pdf');

IFNMG-ESTAGIO/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{{url('/img/logoFinal.png')}}" type="image/png" />

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>IFNMG - Estágio</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    
    <!-- BOOTSTRAP DATEPICKER -->
    <link href="{{ asset('css/components/bootstrap-datepicker/bootstrap-datepicker.min.css')}}" rel="stylesheet">
    <!--/ BOOTSTRAP DATEPICKER -->

    <!-- SELECT2 COM BUSCA -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" /> 
    <!--/ SELECT2 COM BUSCA -->

    <!-- DATA TABLE -->
    <link href="{{ asset('css/components/data-table/datatables.min.css')}}" rel="stylesheet">
    <!--/ DATA TABLE -->
    
    <!-- ICONS -->
    <link href="https://cdn.materialdesignicons.com/3.2.89/css/materialdesignicons.min.css" rel="stylesheet">
    <!--/ ICONS -->

    <style>
	    .navbar-style {
		background: #ddd;
		color: #000;
	    }
	    .navbar-style li:hover {
   		color: #fff; // links
	   }
        /* Tooltip */
        .alerta + .tooltip > .tooltip-inner {
              background-color: #f2dede; 
              color: #a94442; 
              border: 1px solid red; 
              padding: 10px;
              font-size: 13px;
        }
        .alerta + .tooltip.top > .tooltip-arrow {
          border-top: 5px solid red;
        }
        
        
        .letra{
            font-size: 20px;
            color: red;
        }
        .letraV{
            font-size: 16px;
            color: green;
            font-stretch: condensed; 
        }
        .letra1{
            font-size: 40px;
            color: red;
        }
        .modalSuperior{
            z-index: 20000;
        }
        .modal-lg{
            width: 1100px !important;
        }
	</style>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-lg navbar-static-top navbar-default">
<!--        <nav class="navbar navbar-default navbar-static-top navbar-style">-->
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-left" href="{{ url('/') }}">
                        <img src="{{URL::asset('img/logo/logo_almenara.jpg')}}" width="150x" style="padding: 2px 0px 5px 0px !important">
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @auth
                            @can('user.admin')
                                <li class="nav_item"><a href="{{ route('documento.indexPublic') }}">Documentos</a></li>
                                <li class="nav_item"><a href="{{ route('curso.index') }}">Cursos</a></li>
                                <li class="nav_item"><a href="{{ route('professor.index') }}">Professores</a></li>
                                <li class="nav_item"><a href="{{ route('convenio.indexPublic') }}">Convênios</a></li>
                                <li class="nav_item"><a href="{{ route('aluno.index') }}">Alunos</a></li>
                                <li class="nav_item"><a href="{{ route('estagio.index') }}">Estágio</a></li>
                            @else
                                <li class="nav_item"><a href="{{ route('documento.indexPublic') }}">Documentos</a></li>
                                <li class="nav_item"><a href="{{ route('convenio.indexPublic') }}">Convênios</a></li>
                            @endcan
                                <li class="nav_item dropdown">
                                    <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
                                        {{ Auth::user()->name }} <span class="caret"></span>
                                    </a>

                                    <ul class="dropdown-menu">
                                        <li>
                                            <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                                Sair
                                            </a>

                                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                                {{ csrf_field() }}
                                            </form>
                                        </li>
                                        @can('user.admin')
                                            <li><a href="{{ route('register') }}">Registrar</a></li>
                                        @endcan
                                        @can('user.verMeuEstagio')
                                            <li><a href="{{ route('aluno.meusEstagios') }}">Meus estágios</a></li>
                                        @endcan
                                    </ul>
                                </li>
                        @else
                            <li class="nav_item"><a href="{{ route('documento.indexPublic') }}">Documentos</a></li>
                            <li class="nav_item"><a href="{{ route('convenio.indexPublic') }}">Convênios</a></li>
                            <li class="nav_item"><a href="{{ route('login') }}">Login</a></li>
                        @endauth
                        
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container">
            <div class="row">
                @yield('content')
            </div>
        </div>
<!--        MODAL CONFIRM SUBMIT -->
        <div class="modal fade modalSuperior" id="confirm-submit-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content"></div>
            </div>
            <div class="modal-dialog">
                <div class="modal-content"></div>
            </div>
            <div class="modal-dialog">
                <div class="modal-content">
                    <div id="modal-participar" class="modal-header bg-danger">
                        <h4 class="modal-title" id="myModalLabel">Confirmação</h4>
                        <button type="button" class="close" data-dismiss="modal"> <span aria-hidden="true" class="">×   </span><span class="sr-only">Fechar</span></button>

                    </div>
                    <div class="modal-body">

                        Deseja excluir o registro?

                    </div>
                    <div class="modal-footer">
                        <button type="button" id="confirm-modal-btn-close" class="btn btn-default" data-dismiss="modal">Fechar</button>
                        <button type="submit" id="confirm-modal-btn-submit" class="btn btn-danger">Excluir</button>
                    </div>
                </div>
            </div>
        </div>
        @yield('modal')
    </div>
     <!-- Tooltip -->
    <script src="https://unpkg.com/tooltip.js@1.3.0/dist/umd/tooltip.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!--/ Tooltip -->
    
    <!-- Scripts -->
<!--    <script src="{{ asset('js/app.js') }}"></script>-->
   
<!--   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>-->
    <!-- SELECT2 COM BUSCA -->
<!--     <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
    <!--/ SELECT2 COM BUSCA -->

    <!-- BOOTSTRAP DATEPICKER -->
    <script src="{{ asset('js/components/bootstrap-datepicker/bootstrap-datepicker.min.js')}}"></script>
    <script src="{{ asset('js/components/bootstrap-datepicker/bootstrap-datepicker.pt-BR.min.js')}}"></script>
    <!--/ BOOTSTRAP DATEPICKER -->

    <!-- JQUERY MASK -->
    <script src="{{ asset('js/components/jquery-mask/jquery.mask.js')}}"></script>
    <!--/ JQUERY MASK -->
    <!-- DATA TABLE -->
    <script src="{{ asset('js/components/data-table/datatables.min.js')}}"></script>
    <!--/ DATA TABLE -->

    @yield('script')
    <script>
        $(document).ready(function() {
            var form;
            
            setTimeout(function() {
                $('.flash-message').fadeOut('slow');
            }, 5000);
            
            if($('.table-ordering')) {
                $('.table-ordering').each(function() {
                    var config = {
                        "language": {
                            "url": "//cdn.datatables.net/plug-ins/1.10.18/i18n/Portuguese-Brasil.json"
                        },
                        scrollY: 500,
                        paging: true,
                    };
                    var scrollY = $(this).attr('table-max-height');
                    if(scrollY)
                        config.scrollY = scrollY;
                    
                    var paging = $(this).attr('table-paging');
                    if(paging == 'false')
                        config.paging = false;
                    $(this).DataTable(config);
                });
            }
            $('[data-toggle="tooltip"]').tooltip('show');
            
            
            //Controle para confirmar exclusão
            $('.form-delete-cofirm').on('submit', function(e) {
                var confirmed = $(this).data('confirmed');
                if (confirmed == false) {
                    e.preventDefault();
                    $('#confirm-submit-modal').modal();
                    form = $(this);
                }
            })
            
            //Controle para confirmar exclusão
            $('#confirm-modal-btn-submit').on('click', function(e) {
                form.data('confirmed', 'true');
                form.submit();
                form = null;
            })
            
            $('#confirm-submit-modal').on('hide.bs.modal', function(e) {
                form = null;
            })
        });
        
        // Função para restringir os valores dos campos que só devem aceitar numeros
        $('.numbersOnly').keyup(function() {
            this.value = this.value.replace(/[^0-9\,]/g, '');
        });
    </script>
</body>
</html>

IFNMG-ESTAGIO/resources/views/layouts/default.blade.php
<!DOCTYPE html>

<html lang="pt">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="icon" href="{{url('/img/logoFinal.png')}}" type="image/png" />


        <title>IFNMG - Estágio</title>
        <link href="{{ asset('css/app.css') }}" rel="stylesheet">

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
        
        <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">
        
        
        <!-- BOOTSTRAP DATEPICKER -->
        <link href="{{ asset('css/components/bootstrap-datepicker/bootstrap-datepicker.min.css')}}" rel="stylesheet">
        <!--/ BOOTSTRAP DATEPICKER -->

        <!-- SELECT2 COM BUSCA -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" /> 
        <!--/ SELECT2 COM BUSCA -->
	
	
	
	
	<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
	<link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.light_green-red.min.css">
	<script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
	
    </head>
    <body>
        <!-- Always shows a header, even in smaller screens. -->
		
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
	<style>
	    .mdl-layout__header {
		background: #ddd;
		color: #000;
	    }
	    .mdl-layout__header__link:hover {
   		color: #fff; // links
	   }
	</style>
    
    <header class="mdl-layout__header">
  
        <div class="mdl-layout__header-row">	
	
        <!-- Title -->
        <span class="mdl-layout-title mdl-layout--large-screen-only"> <img src="{{URL::asset('img/loogo.png')}}" height="30%" width="225x"></span>
        <!-- Add spacer, to align navigation to the right -->
        <div class="mdl-layout-spacer"></div>
        <!-- Navigation. We hide it in small screens. -->
        <nav class="mdl-navigation mdl-layout--large-screen-only">
            @auth
                <a class="mdl-navigation__link" href="{{ route('documento.indexPublic') }}">Documentos</a>
                <a class="mdl-navigation__link" href="{{ route('curso.index') }}">Cursos</a>
                <a class="mdl-navigation__link" href="{{ route('professor.index') }}">Professores</a>
                <a class="mdl-navigation__link" href="{{ route('convenio.indexPublic') }}">Convênios</a>
                <a class="mdl-navigation__link" href="{{ route('aluno.index') }}">Alunos</a>
                <a class="mdl-navigation__link" href="{{ route('estagio.index') }}">Estágio</a>

                <button id="demo-menu-top-right"
                class="mdl-button mdl-js-button mdl-button--icon">
                    <i class="material-icons">more_vert</i>
                </button>

                <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect" data-mdl-for="demo-menu-top-right">
                    <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                        <li class="mdl-menu__item"> Sair</li>
                    </a>
                    <a href="{{ route('register') }}">
                        <li class="mdl-menu__item"> Registrar</li>
                    </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        {{ csrf_field() }}
                    </form>
                </ul>
            @else
                <a class="mdl-navigation__link" href="{{ route('documento.indexPublic') }}">Documentos</a>
                <a class="mdl-navigation__link" href="{{ route('convenio.indexPublic') }}">Convênios</a>
                
                <button id="demo-menu-top-right"
                class="mdl-button mdl-js-button mdl-button--icon">
                    <i class="material-icons">more_vert</i>
                </button>

                <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect" data-mdl-for="demo-menu-top-right">
                    <a href="{{ route('login') }}">
                        <li class="mdl-menu__item">Entrar</li>
                    </a>
                </ul>
        @endauth
        </nav>
    </div>
  </header>
  <div class="mdl-layout__drawer mdl-layout--small-screen-only">
    <span class="mdl-layout-title"><img src="{{URL::asset('img/logo3.png')}}" height="30%" width="200x"></span>
    <nav class="mdl-navigation">
        @auth
            <a class="mdl-navigation__link" href="{{ route('documento.indexPublic') }}">Documentos</a>
            <a class="mdl-navigation__link" href="{{ route('curso.index') }}">Cursos</a>
            <a class="mdl-navigation__link" href="{{ route('aluno.index') }}">Alunos</a>
            <a class="mdl-navigation__link" href="{{ route('professor.index') }}">Professores</a>
            <a class="mdl-navigation__link" href="{{ route('convenio.indexPublic') }}">Convênios</a>
            <a class="mdl-navigation__link" href="{{ route('estagio.index') }}">Estágio</a>

            <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                <li class="mdl-navigation__link"> Sair</li>
            </a>
            <a href="{{ route('register') }}">
                <li class="mdl-navigation__link"> Registrar</li>
            </a>

            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                {{ csrf_field() }}
            </form>
        @else
            <a class="mdl-navigation__link" href="{{ route('documento.indexPublic') }}">Documentos</a>
            <a class="mdl-navigation__link" href="{{ route('convenio.indexPublic') }}">Convênios</a>
            <a href="{{ route('login') }}">
                <li class="mdl-navigation__link">Entrar</li>
            </a>
        @endauth
    </nav>
  </div>
  
   <main class="mdl-layout__content">
    <div class="page-content"><!-- Your content goes here -->
	
	 <div class="container">
            @yield('content')
        </div>
        
        <script src="{{ asset('js/app.js')}}"></script>

        <!-- SELECT2 COM BUSCA -->
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
        <!--/ SELECT2 COM BUSCA -->

        <!-- BOOTSTRAP DATEPICKER -->
        <script src="{{ asset('js/components/bootstrap-datepicker/bootstrap-datepicker.min.js')}}"></script>
        <script src="{{ asset('js/components/bootstrap-datepicker/bootstrap-datepicker.pt-BR.min.js')}}"></script>
        <!--/ BOOTSTRAP DATEPICKER -->
        
        <!-- JQUERY MASK -->
        <script src="{{ asset('js/components/jquery-mask/jquery.mask.js')}}"></script>
        <!--/ JQUERY MASK -->

        @yield('script')
	
	</div>
  </main>
</div>
        
       
        @yield('modal')
    </body>
</html>

IFNMG-ESTAGIO/resources/views/layouts/email.blade.php
@component('mail::message')
{{-- Greeting --}}
@if (! empty($greeting))
# {{ $greeting }}
@else
@if ($level == 'error')
# Opa!
@else
# Olá!
@endif
@endif

{{-- Intro Lines --}}
@foreach ($introLines as $line)
{{ $line }}

@endforeach

{{-- Action Button --}}
@isset($actionText)
<?php
    switch ($level) {
        case 'success':
            $color = 'green';
            break;
        case 'error':
            $color = 'red';
            break;
        default:
            $color = 'blue';
    }
?>
@component('mail::button', ['url' => $actionUrl, 'color' => $color])
{{ $actionText }}
@endcomponent
@endisset

{{-- Outro Lines --}}
@foreach ($outroLines as $line)
{{ $line }}

@endforeach

{{-- Salutation --}}
@if (! empty($salutation))
{{ $salutation }}
@else
Grato,<br>{{ config('app.name') }}
@endif

{{-- Subcopy --}}
@isset($actionText)
@component('mail::subcopy')
Se estiver enfrentando problemas clickando no "{{ $actionText }}" botão, copie e cole a URL abaixo no seu navegador: [{{ $actionUrl }}]({{ $actionUrl }})
@endcomponent
@endisset
@endcomponent

IFNMG-ESTAGIO/resources/views/layouts/pdf.blade.php
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="css/components/bootstrap.min.css">
    <style>
    	.col {
    		float: left;
    	}/*
    	.col-1 {
    		width: 10%;
    	}
    	.col-2 {
    		width: 20%;
    	}
    	.col-4 {
    		width: 40%;
    	}
    	.col-6 {
    		width: 60%;
    	}
    	.col-8 {
    		width: 80%;
    	}
    	.col-1 {
    		width: 10%;
    	}
    	.col-10 {
    		width: 100%;
    	}*/

    	.container {
    		margin-left: 0px;
    		margin-right: 0px;
    		width: 100% !important;
    		max-width: none !important;
    		padding-left: .6604cm;
    		padding-right: .6604cm;
    	}
    	hr {
		    border: none;
		    height: 3px;
		    /* Set the hr color */
		    color: #333; /* old IE */
		    background-color: #333; /* Modern Browsers */
		}
	</style>
  </head>
  <body>
      <div class="container">
          @yield('content')
      </div>
  </body>
</html>