IFNMG-ESTAGIO/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', function () {
    return view('welcome');
})->name('/');

Route::group(['middleware' => ['can:user.admin']], function() {
    Route::post('/aluno','AlunoController@index')->name('aluno.filtro');
    Route::resource('aluno','AlunoController');
    Route::get('/aluno/{aluno_id}/pdf/{documento}','AlunoController@showPdf')->name('aluno.pdf');
    Route::get('/aluno/{aluno_id}/fotos/{foto}','AlunoController@showFoto')->name('aluno.foto');
    Route::post('/aluno/{aluno_id}/destroyPdf','AlunoController@destroyPdf')->name('aluno.destroyPdf');

    Route::resource('areaAtuacao','AreaAtuacaoController');

    Route::resource('convenio','ConveniosController');
    Route::get('/convenio/{convenio_id}/pdf/cadastro_convenio','ConveniosController@showPdf')->name('convenio.pdf');
    Route::post('/convenio/{convenio_id}/destroyPdf','ConveniosController@destroyPdf')->name('convenio.destroyPdf');

    Route::resource('curso','CursoController');
    Route::resource('estagio','EstagiosController');
    Route::get('/estagio/create/{aluno_id}','EstagiosController@create')->name('estagio.create()');
    Route::get('/estagio/{estagio_id}/edit/{aluno_id}','EstagiosController@edit')->name('estagio.edit()');
    Route::get('/estagio/{estagio_id}/pdf/{documento}','EstagiosController@showPdf')->name('estagio.pdf');
    Route::post('/estagio/{estagio_id}/destroyPdf','EstagiosController@destroyPdf')->name('estagio.destroyPdf');
    Route::delete('/estagio/{estagio_id}/destroy/{aluno_id}','EstagiosController@destroy')->name('estagio.destroy()');

    Route::resource('pessoa','PessoaController');

    Route::resource('professor','ProfessoresController');
    Route::resource('documento','DocumentosController');

});
Route::group(['middleware' => ['can:user.verMeuEstagio']], function() {
    Route::get('/meusEstagios','AlunoController@meusEstágios')->name('aluno.meusEstagios');
    Route::get('/meusEstagios/{aluno_id}','AlunoController@meusEstágios')->name('aluno.meuEstagio');
    Route::get('/estagio/{estagio_id}/pdf/{documento}','EstagiosController@showPdf')->name('estagio.pdf');
});

Route::get('/convenio','ConveniosController@index')->name('convenio.indexPublic');
Route::get('/documento','DocumentosController@index')->name('documento.indexPublic');
Route::get('/home', 'HomeController@index')->name('home');

Route::get('/convenio/public/{convenio}','ConveniosController@show')->name('convenio.abrir');
Route::get('/documento/public/{documentos}','DocumentosController@show')->name('documento.abrir');
Route::get('/convenio/{convenio_id}/pdf/cadastro_convenio','ConveniosController@showPdf')->name('convenio.pdf');

IFNMG-ESTAGIO/resources/views/professor/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Adicionar novo Professor</h2>
            </div>
            <a href="{{ route('professor.index') }}">
                <div class="btn btn-danger pull-right">
                    Voltar
                </div>
			</a>
        </div>
    </div>

    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Opa!</strong> Tem algo de errado com as suas entradas.<br><br>
            
        </div>
    @endif
    {!! Form::open(array('route' => 'professor.store','method'=>'POST')) !!}

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <label>Campos com <span class="mdi mdi-asterisk" style="color: red"></span> são obrigatórios</label>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <label for="nome">
                    <strong>Nome<span class="mdi mdi-asterisk" style="color: red"></span>:</strong>
                </label>
                @if ($errors->has('nome'))
                    <span class="alerta" tabindex="0" data-toggle="tooltip" data-placement="top" title="{{ $errors->first('nome') }}">
                        <img src="{{url('/img/alert-outline.png')}}"/>
                    </span>
                @endif
                {!! Form::text('nome', null, array('placeholder' => 'Professor','class' => 'form-control', 'maxlength' => 100)) !!}
            </div>
        </div>
        
		<div class="col-xs-12 col-sm-12 col-md-12">
			<div class="form-group">
				<label for="email">
                    <strong>Email<span class="mdi mdi-asterisk" style="color: red"></span>:</strong>
                </label>
                @if ($errors->has('email'))
                    <span class="alerta" tabindex="0" data-toggle="tooltip" data-placement="top" title="{{ $errors->first('email') }}">
                        <img src="{{url('/img/alert-outline.png')}}"/>
                    </span>
                @endif
				{!! Form::email('email', null, array('multiple' => 'multiple', 'class' => 'form-control')) !!}
			</div>
		</div>

        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-success"> ENVIAR </button>
        </div>

    </div>
    {!! Form::close() !!}
</div>
@endsection

@section('script')
    <script>
        $('select[name="curso_id[]"]').select2();
    </script>
@endsection

IFNMG-ESTAGIO/resources/views/professor/edit.blade.php
@extends('layouts.app')
 
@section('content')
<div class="container">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Editar Professor</h2>
            </div>
            <a href="{{ route('professor.index') }}">
                <div class="btn btn-danger pull-right" style="margin-top: 5px">
                    Voltar
                </div>
			</a>
        </div>
    </div>

    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Opa!</strong> Tem algo de errado com as suas entradas.<br><br>
        </div>
    @endif

    {!! Form::model($professor, ['method' => 'PATCH','route' => ['professor.update', $professor->id]]) !!}
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <label>Campos com <span class="mdi mdi-asterisk" style="color: red"></span> são obrigatórios</label>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <label for="nome">
                    <strong>Nome<span class="mdi mdi-asterisk" style="color: red"></span>:</strong>
                </label>
                @if ($errors->has('nome'))
                    <span class="alerta" tabindex="0" data-toggle="tooltip" data-placement="top" title="{{ $errors->first('nome') }}">
                        <img src="{{url('/img/alert-outline.png')}}"/>
                    </span>
                @endif
                {!! Form::text('nome', $professor->nome, array('placeholder' => 'Nome','class' => 'form-control', 'maxlength' => 100)) !!}
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <label for="email">
                    <strong>Email<span class="mdi mdi-asterisk" style="color: red"></span>:</strong>
                </label>
                @if ($errors->has('email'))
                    <span class="alerta" tabindex="0" data-toggle="tooltip" data-placement="top" title="{{ $errors->first('email') }}">
                        <img src="{{url('/img/alert-outline.png')}}"/>
                    </span>
                @endif
                {!! Form::email('email', $professor->email, array('placeholder' => 'Email','class' => 'form-control', 'maxlength' => 100)) !!}
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-success"> ENVIAR </button>
        </div>

    </div>
    {!! Form::close() !!}
</div>
@endsection

@section('script')
    <script>
        $('select[name="curso_id[]"]').select2();
    </script>
@endsection

IFNMG-ESTAGIO/resources/views/professor/index.blade.php
@extends('layouts.app')
 
@section('content')
<div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">

                @if ($message = Session::get('success'))
                    <div class="alert alert-success">
                        <p>{{ $message }}</p>
                    </div>
                @endif
                @if ($message = Session::get('error'))
                    <div class="alert alert-danger">
                        <p>{{ $message }}</p>
                    </div>
                @endif
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-md-9">Listagem de Professores</div>
                            @can('user.admin')
                                <div class="text-right col-md-3"><a class="btn btn-default btn-sm" href="{{ route('professor.create') }}" role="button">Novo Professor</a></div>
                            @endcan
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped table-ordering" >
                                <thead>
                                    <tr>
                                        <th>Nome</th>
                                        <th width="200px">Ação</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($professores as $key => $professor)
                                    <tr>
                                        <td>{{ $professor->nome }}</td>
                                        <td>
                                            <a class="btn btn-default btn-sm" href="{{ route('professor.show',$professor->id) }}">Abrir</a>
                                            <a class="btn btn-primary btn-sm" href="{{ route('professor.edit',$professor->id) }}">Editar</a>
                                            {!! Form::open(['method' => 'DELETE','route' => ['professor.destroy', $professor->id],'style'=>'display:inline','class'=>'form-delete-cofirm', 'data-confirmed'=>'false']) !!}
                                            {!! Form::submit('Delete', ['class' => 'btn btn-danger btn-sm']) !!}
                                            {!! Form::close() !!}
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

IFNMG-ESTAGIO/resources/views/professor/show.blade.php
@extends('layouts.app')
 
@section('content')
<div class="container">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Visualização de Professor</h2>
            </div>
            <a href="{{ route('professor.index') }}">
                <div class="btn btn-danger pull-right">
                    Voltar
                </div>
			</a>
        </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Nome:</strong>
            {{ $professor->nome }}
        </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>E-mail:</strong>
            {{ $professor->email }}
        </div>
    </div>
</div>

@endsection