IFNMG-ESTAGIO/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', function () {
    return view('welcome');
})->name('/');

Route::group(['middleware' => ['can:user.admin']], function() {
    Route::post('/aluno','AlunoController@index')->name('aluno.filtro');
    Route::resource('aluno','AlunoController');
    Route::get('/aluno/{aluno_id}/pdf/{documento}','AlunoController@showPdf')->name('aluno.pdf');
    Route::get('/aluno/{aluno_id}/fotos/{foto}','AlunoController@showFoto')->name('aluno.foto');
    Route::post('/aluno/{aluno_id}/destroyPdf','AlunoController@destroyPdf')->name('aluno.destroyPdf');

    Route::resource('areaAtuacao','AreaAtuacaoController');

    Route::resource('convenio','ConveniosController');
    Route::get('/convenio/{convenio_id}/pdf/cadastro_convenio','ConveniosController@showPdf')->name('convenio.pdf');
    Route::post('/convenio/{convenio_id}/destroyPdf','ConveniosController@destroyPdf')->name('convenio.destroyPdf');

    Route::resource('curso','CursoController');
    Route::resource('estagio','EstagiosController');
    Route::get('/estagio/create/{aluno_id}','EstagiosController@create')->name('estagio.create()');
    Route::get('/estagio/{estagio_id}/edit/{aluno_id}','EstagiosController@edit')->name('estagio.edit()');
    Route::get('/estagio/{estagio_id}/pdf/{documento}','EstagiosController@showPdf')->name('estagio.pdf');
    Route::post('/estagio/{estagio_id}/destroyPdf','EstagiosController@destroyPdf')->name('estagio.destroyPdf');
    Route::delete('/estagio/{estagio_id}/destroy/{aluno_id}','EstagiosController@destroy')->name('estagio.destroy()');

    Route::resource('pessoa','PessoaController');

    Route::resource('professor','ProfessoresController');
    Route::resource('documento','DocumentosController');

});
Route::group(['middleware' => ['can:user.verMeuEstagio']], function() {
    Route::get('/meusEstagios','AlunoController@meusEstágios')->name('aluno.meusEstagios');
    Route::get('/meusEstagios/{aluno_id}','AlunoController@meusEstágios')->name('aluno.meuEstagio');
    Route::get('/estagio/{estagio_id}/pdf/{documento}','EstagiosController@showPdf')->name('estagio.pdf');
});

Route::get('/convenio','ConveniosController@index')->name('convenio.indexPublic');
Route::get('/documento','DocumentosController@index')->name('documento.indexPublic');
Route::get('/home', 'HomeController@index')->name('home');

Route::get('/convenio/public/{convenio}','ConveniosController@show')->name('convenio.abrir');
Route::get('/documento/public/{documentos}','DocumentosController@show')->name('documento.abrir');
Route::get('/convenio/{convenio_id}/pdf/cadastro_convenio','ConveniosController@showPdf')->name('convenio.pdf');

IFNMG-ESTAGIO/app/Documentos.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Documentos extends Model
{
    protected $table = 'documento';
    public $fillable = ['id','nome','descricao','arquivo', 'arquivo_pdf', 'access'];
    protected $hidden = ['access'];
}

IFNMG-ESTAGIO/app/Http/Controllers/DocumentosController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Redirect;

use Auth;
use App\Documentos;

class DocumentosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $access = Auth::user()->access ?? env('APP_ACCESS');
        
        $documentos = Documentos::where('access', $access)->orderBy('id','DESC')->get();
        return view('documento.index',compact('documentos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('documento.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'nome' => 'required',
            'descricao' => 'required',
            'arquivo' => 'required',
            'arquivo_pdf' => 'required|mimes:pdf',
        ],[
            'required' => 'Este campo é obrigatório.',
            'mimes' => 'Formato do arquivo deve ser PDF'
        ]);
        
        // Adição do controle de acesso
        $request['access'] = Auth::user()->access;
        
        $documento = Documentos::where('nome',$request->nome)->first();
        if($documento) {
            $errorMessage[] = 'Nome já cadastrado.';
            
            return Redirect::back()->withInput(Input::all())->with('error', 'Nome já cadastrado.');
        }
        
        $documento = Documentos::create(
            [
                'nome' => $request->nome,
                'descricao' => $request->descricao,
                'arquivo' => $request->arquivo->getClientOriginalName(),
                'arquivo_pdf' => $request->arquivo_pdf->getClientOriginalName(),
                'access'=> $request['access']
            ]
        );
        
        if($request->file('arquivo') != null) {
            $path_file = $request->file('arquivo')->storeAs("documentos","{$documento->arquivo}");
        }
        
        if($request->file('arquivo_pdf') != null) {
            $path_file = $request->file('arquivo_pdf')->storeAs("documentos","{$documento->arquivo_pdf}");
        }

        return redirect()->route('documento.indexPublic')
                        ->with('success','Registro salvo com sucesso');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($documento)
    {
        
        $file_path = "documentos/$documento";
        
        if(Storage::disk('local')->exists("/$file_path"))
            return response()->file(storage_path("app/$file_path"));
        
        return abort(404, "Documento não foi encontrado");
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Documentos  $documento
     * @return \Illuminate\Http\Response
     */
    public function edit(Documentos $documento)
    {
        if (Gate::denies('documento.controlar', $documento)) {
            return abort(403, "Você não tem acesso a esta função");
        }
        
        return view('documento.edit',compact('documento'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  Documentos  $documento
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Documentos $documento)
    {
        if (Gate::denies('documento.controlar', $documento)) {
            return abort(403, "Você não tem acesso a esta função");
        }
        
        $this->validate($request, [
            'nome' => 'required',
            'descricao' => 'required',
            'arquivo_pdf' => 'mimes:pdf',
        ],[
            'required' => 'Este campo é obrigatório.',
            'mimes' => 'Formato do arquivo deve ser PDF'
        ]);
        
        $error = Documentos::where('nome',$request->nome)
            ->where('id', '!=',  $documento->id)
            ->first();
        
        if($error) {
            $errorMessage[] = 'Nome já cadastrado.';
            
            return Redirect::back()->withInput(Input::all())->withErrors($errorMessage);
        }
        
        if($request->file('arquivo')) {
            $path_file = $request->file('arquivo')->storeAs("documentos",$request->arquivo->getClientOriginalName());
            $path_file_pdf = $request->file('arquivo_pdf')->storeAs("documentos",$request->arquivo_pdf->getClientOriginalName());
            $documento->update(
                [
                    'nome' => $request->nome,
                    'descricao' => $request->descricao,
                    'arquivo' => $request->arquivo->getClientOriginalName(),
                    'arquivo_pdf' => $request->arquivo_pdf->getClientOriginalName()
                ]
            );
        } else {
            $documento->update($request->all());
        }
        return redirect()->route('documento.indexPublic')
                        ->with('success','Registro alterado com sucesso');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Documentos  $documento
     * @return \Illuminate\Http\Response
     */
    public function destroy(Documentos $documento)
    {
        if (Gate::denies('documento.controlar', $documento)) {
            return abort(403, "Você não tem acesso a esta função");
        }
        
        $documento->delete();
        return redirect()->route('documento.indexPublic')
                        ->with('success','Registro deletado com sucesso');
    }
}

IFNMG-ESTAGIO/resources/views/documento/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-lg-12 margin-tb">
                <div class="pull-left">
                    <h2>Adicionar novo Documento</h2>
                </div>
                <a href="{{ route('documento.indexPublic') }}">
                    <div class="btn btn-danger pull-right">
                        Voltar
                    </div>
                </a>
            </div>
        </div>

        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <strong>Opa!</strong> Tem algo de errado com as suas entradas.<br><br>
            </div>
        @endif
        
        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
        @if ($message = Session::get('error'))
            <div class="alert alert-danger">
                <p>{{ $message }}</p>
            </div>
        @endif

        {!! Form::open(array('route' => 'documento.store', 'enctype' =>'multipart/form-data', 'method'=>'POST')) !!}
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <label>Campos com <span class="mdi mdi-asterisk" style="color: red"></span> são obrigatórios</label>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <label for="nome">
                        <strong>Nome<span class="mdi mdi-asterisk" style="color: red"></span>:</strong>
                    </label>
                    @if ($errors->has('nome'))
                        <span class="alerta" tabindex="0" data-toggle="tooltip" data-placement="top" title="{{ $errors->first('nome') }}">
                            <img src="{{url('/img/alert-outline.png')}}"/>
                        </span>
                    @endif
                    {!! Form::text('nome', null, array('placeholder' => 'Nome', 'class' => 'form-control')) !!}
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <label for="descricao">
                        <strong>Descrição<span class="mdi mdi-asterisk" style="color: red"></span>: </strong>
                    </label>
                    @if ($errors->has('descricao'))
                        <span class="alerta" tabindex="0" data-toggle="tooltip" data-placement="top" title="{{ $errors->first('descricao') }}">
                            <img src="{{url('/img/alert-outline.png')}}"/>
                        </span>
                    @endif
                    {!! Form::text('descricao', null, array('placeholder' => 'Descrição', 'class' => 'form-control')) !!}
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <label for="arquivo">
                        <strong>Arquivo<span class="mdi mdi-asterisk" style="color: red"></span>:</strong>
                    </label>
                    @if ($errors->has('arquivo'))
                        <span class="alerta" tabindex="0" data-toggle="tooltip" data-placement="top" title="{{ $errors->first('arquivo') }}">
                            <img src="{{url('/img/alert-outline.png')}}"/>
                        </span>
                    @endif
                    {!! Form::file('arquivo', array('class' => 'form-control')) !!}
                </div>
            </div>
            
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <label for="arquivo">
                        <strong>Arquivo PDF<span class="mdi mdi-asterisk" style="color: red"></span>:</strong>
                    </label>
                    @if ($errors->has('arquivo_pdf'))
                        <span class="alerta" tabindex="0" data-toggle="tooltip" data-placement="top" title="{{ $errors->first('arquivo_pdf') }}">
                            <img src="{{url('/img/alert-outline.png')}}"/>
                        </span>
                    @endif
                    {!! Form::file('arquivo_pdf', array('class' => 'form-control')) !!}
                </div>
            </div>


            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-success"> ENVIAR </button>
            </div>

        </div>
    </div>
    {!! Form::close() !!}
@endsection

IFNMG-ESTAGIO/resources/views/documento/edit.blade.php
@extends('layouts.app')
 
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-lg-12 margin-tb">
                <div class="pull-left">
                    <h2>Editar Documento</h2>
                </div>
                <a href="{{ route('documento.indexPublic') }}">
                    <div class="btn btn-danger pull-right">
                        Voltar
                    </div>
                </a>
            </div>
        </div>

        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <strong>Opa!</strong> Tem algo de errado com as suas entradas.<br><br>
            </div>
        @endif

        {!! Form::model($documento, ['method' => 'PATCH', 'enctype' =>'multipart/form-data', 'route' => ['documento.update', $documento->id]]) !!}
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <label>Campos com <span class="mdi mdi-asterisk" style="color: red"></span> são obrigatórios</label>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <label for="nome">
                        <strong>Nome<span class="mdi mdi-asterisk" style="color: red"></span>:</strong>
                    </label>
                    @if ($errors->has('nome'))
                        <span class="alerta" tabindex="0" data-toggle="tooltip" data-placement="top" title="{{ $errors->first('nome') }}">
                            <img src="{{url('/img/alert-outline.png')}}"/>
                        </span>
                    @endif
                    {!! Form::text('nome', $documento->nome, array('placeholder' => 'Nome', 'class' => 'form-control')) !!}
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <label for="descricao">
                        <strong>Descrição<span class="mdi mdi-asterisk" style="color: red"></span>: </strong>
                    </label>
                    @if ($errors->has('descricao'))
                        <span class="alerta" tabindex="0" data-toggle="tooltip" data-placement="top" title="{{ $errors->first('descricao') }}">
                            <img src="{{url('/img/alert-outline.png')}}"/>
                        </span>
                    @endif
                    {!! Form::text('descricao', $documento->descricao, array('placeholder' => 'Descrição', 'class' => 'form-control')) !!}
                </div>
            </div>
            <div class="col-md-10">
                <div class="form-group">
                    <strong>Arquivo<span class="mdi mdi-asterisk" style="color: red"></span>:</strong>
                    {!! Form::file('arquivo', array('class' => 'form-control file')) !!}
                </div>
            </div>

            <div class="col-md-2">
                <div class="form-group">
                    <br>
                    <a class='btn btn-default' href="{{route('documento.show',$documento->arquivo)}}" target="_blank">Visualizar</a>
                </div>
            </div>
            
            <div class="col-md-10">
                <div class="form-group">
                    <strong>Arquivo PDF<span class="mdi mdi-asterisk" style="color: red"></span>:</strong>
                    @if ($errors->has('arquivo_pdf'))
                        <span class="alerta" tabindex="0" data-toggle="tooltip" data-placement="top" title="{{ $errors->first('arquivo_pdf') }}">
                            <img src="{{url('/img/alert-outline.png')}}"/>
                        </span>
                    @endif
                    {!! Form::file('arquivo_pdf', array('class' => 'form-control file')) !!}
                </div>
            </div>

            <div class="col-md-2">
                <div class="form-group">
                    <br>
                    <a class='btn btn-default' href="{{route('documento.show',$documento->arquivo_pdf)}}" target="_blank">Visualizar</a>
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-success"> ENVIAR </button>
            </div>
        </div>
    {!! Form::close() !!}
</div>
@endsection

IFNMG-ESTAGIO/resources/views/documento/index.blade.php
@extends('layouts.app')
 
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                
                @if ($message = Session::get('success'))
                    <div class="alert alert-success">
                        <p>{{ $message }}</p>
                    </div>
                @endif
                @if ($message = Session::get('error'))
                    <div class="alert alert-danger">
                        <p>{{ $message }}</p>
                    </div>
                @endif
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-md-9">Listagem de Documentos</div>
                            @can('user.admin')
                                <div class="text-right col-md-3"><a class="btn btn-default btn-sm" href="{{ route('documento.create') }}" role="button">Novo Documento</a></div>
                            @endcan
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped table-ordering" table-paging="false" >
                                <thead>
                                    <tr>
                                        <th>Nome</th>
                                        <th class="hidden-sm-down">Descrição</th>
                                        <th width="230px">Ação</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($documentos as $key => $documento)
                                        <tr>
                                            <td>{{ $documento->nome }}</td>
                                            <td class="hidden-sm-down">{{ (strlen($documento->descricao)>100)?substr($documento->descricao,0,97).'...': $documento->descricao }}</td>
                                            <td class=" text-center">
                                                <a class="btn btn-default btn-sm" target="_blank" href="{{ route('documento.abrir',$documento->arquivo) }}">Visualizar</a>
                                                <a class="btn btn-default btn-sm" target="_blank" href="{{ route('documento.abrir',$documento->arquivo_pdf) }}">PDF</a>
                                                @can('user.admin')
                                                    <a class="btn btn-primary btn-sm" href="{{ route('documento.edit',$documento->id) }}">Editar</a>
                                                    {!! Form::open(['method' => 'DELETE','route' => ['documento.destroy', $documento->id],'style'=>'display:inline','class'=>'form-delete-cofirm', 'data-confirmed'=>'false']) !!}
                                                    {!! Form::submit('Excluir', ['class' => 'btn btn-danger btn-sm']) !!}
                                                    {!! Form::close() !!}
                                                @endcan
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection